sign-up and logout functionality complete, WIP login.
Aerolyzer/Aerolyzer_App pull request #14
Opened 2017-03-03 01:05 UTC by liusop

The sign up and logout both work, but we are still working on the login. We also need to rebase settings.py because of a conflict.

2017-03-06 20:02 UTC, liusop commented
@kwhitehall login feature now functional

2017-03-07 13:33 UTC, kwhitehall commented
Nice one @liusop and @colliell. Did some testing on my end and got it up and running. 
Please update the README with this PR as well. 
Important things to note are: 
1. Postgresql 9.5.g (min requirement) should be installed and running on port 5432 (provide download link for postgresql)
2. The database in Postgresql should be set up with the settings as outlined in settings.py namely:
NAME, USER and PASSWORD settings. 

Finally on the signup page, please allow for the user to enter credentials OR do not show the login and password box on the sign in page until the person signs up. Currently, if you access the signup page, then enter your details the information is not accepted unless the 'sign up'  was completed. As such it may be desirable to show the first visit to the sign in page without log in credentials. (Any page with login and password box should take info by default). Please see screenshot for further explanation of the issue. Feel free to discuss on Slack channel as well. 

![signup](https://cloud.githubusercontent.com/assets/7198635/23658398/660b4070-0310-11e7-9242-0219d9055ee8.png)

2017-03-07 13:52 UTC, kwhitehall submitted a review, later dismissed

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/Aerolyzer/settings.py
> +        'ENGINE': 'django.db.backends.postgresql',  # 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
please remove these comments (cleaner code).

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/app/forms.py
> +    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("Must contain only letters, number
split line. Same for the others. Line length shouldn't exceed 100 characters (as per our Python linting standards)

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/app/templates/app/faq.html
> -
on line 5, " is missing, should be 
<div class="container" style="height: 375px;">

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/app/templates/app/profile.html
> +	<div class="container" style="height: 375px;>
add " to close style

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/app/templates/app/upload.html
> +	<div class="container" style="height: 375px;>
add  "

2017-03-07 13:52 UTC, kwhitehall commented on Aerolyzer/app/urls.py
remove white space in lib imports

2017-03-07 14:03 UTC, kwhitehall requested changes
This is looking good guys! 
Please address these "linting" issues before merging.

2017-03-08 00:29 UTC, kwhitehall requested changes
Thank you for addressing the concerns. A few more are here to be addressed before merging please.

2017-03-08 00:29 UTC, kwhitehall commented on Aerolyzer/Aerolyzer/settings.py
>  django.contrib.auth.LOGIN_URL = '/'
move this line after all the imports

2017-03-08 00:29 UTC, kwhitehall commented on Aerolyzer/app/templates/app/base.html
> +                <a lass="navbar-brand page-scroll" href="#page-top">Aerolyzer</a>
Think this is a typo here.

2017-03-08 00:29 UTC, kwhitehall commented on Aerolyzer/app/views.py
> +	return render(request, 'app/index.html', {'user': request.user, 'is_index':True,},)
should there be a comma before the brace?

2017-03-08 00:29 UTC, kwhitehall commented on README.md
> +<<<<<<< HEAD
remove these git conflict comments i.e.  <<<<<<< HEAD and >>>>>>> 8bcb558c2c76cab7363834d64753975e922d55dc

2017-03-08 00:31 UTC, kwhitehall commented on README.md
> +1.Postgresql 9.5.g (min requirement) should be installed and running on port 5432. Postgresql can be downloaded at https://www.postgresql.org/download/
Check PostgreSql version.

2017-03-08 00:32 UTC, kwhitehall commented on README.md
> +NAME, USER and PASSWORD settings.
Please indicate what these values should be.

2017-03-08 17:16 UTC, kwhitehall commented on Aerolyzer/app/static/js/dropzone.js
> +
@liusop  please remove this file from this commit.

2017-03-08 17:29 UTC, kwhitehall commented
Thanks! @liusop and @colliell. 
Merging this. Great work! 
Re the dropzone.js if it is to be added to code base, open up an issue for it and add make a separate PR.

2017-03-08 17:29 UTC, kwhitehall approved these changes

2017-03-08 17:30 UTC, merged